ci: attempt to get upgrades manifest from previous job, otherwise fallback to commited one

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -62,11 +62,20 @@ variables:
 .download-smart-contract-artifacts: &download-smart-contract-artifacts
   - echo "Downloading artifacts from previous successful deploy" 
   - echo "Downloading artifacts from $UPGRADE_JOB_NAME"
-  - 'curl --fail --location --output artifacts.zip --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=$UPGRADE_JOB_NAME"'
-  - 'if [ ! -f "artifacts.zip" ]; then echo "cannot find update artifacts, trying from $DEPLOY_JOB_NAME" && curl --fail --location --output artifacts.zip --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=$DEPLOY_JOB_NAME"; fi'
-  - 'if [ ! -f "artifacts.zip" ]; then echo "cannot find deploy artifacts, skipping update" && exit 1; fi'
-  - unzip artifacts.zip "Goerli/clonefactory/.openzeppelin" -d . 
-  - echo "artifacts downloaded" 
+  - | 
+    set +e
+    curl --fail --location --output artifacts.zip --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=$UPGRADE_JOB_NAME"
+    if [ $? -ne 0 ]; then
+      echo "cannot find update artifacts, trying from $DEPLOY_JOB_NAME"
+      curl --fail --location --output artifacts.zip --header "PRIVATE-TOKEN: $GITLAB_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/main/download?job=$DEPLOY_JOB_NAME"
+      if [ $? -ne 0 ]; then
+        echo "cannot find deploy artifacts, skipping update"
+        exit 0 
+      fi
+    fi
+    set -e
+  - if [ -f artifacts.zip ]; then unzip artifacts.zip "Goerli/clonefactory/.openzeppelin" -d . && echo "artifacts downloaded";  fi
+  - if [ ! -f artifacts.zip ]; then echo "artifacts not downloaded"; fi
 
 # Deploys clonefactory to the blockchain using env variables from the corresponding environment
 # Updates the environment url to the etherscan url of the contract
